### ISSUE TITLE
Performance on DUT

### ISSUE THREAD

**Issue by Angknpng** [taozh2017/SPNet#4]
Have you evaluted the model on DUT-RGBD? I have used the code test_performance_maps.py and the model 'SPNet_best.pth' you provided to predicet the salient maps. However, the results is different from you gived in the paper, including the NJUD. Is there anything wrong? 
I hope for your reply! Thanks!

**Comment by taozh2017** [comment]
Which evaluation toolbox do you use? There is a little difference between Python evaluation and Matlab version.

**Comment by Angknpng** [comment]
I used the Matlab&nbsp;valuation toolbox.&nbsp;In general, there is little difference between the two Toolbox, but there is a big difference between the results I tested here. I suspect that the model you provided is not optimal, or there is something wrong there. Could you provide the predicted results on DUT?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tao ***@***.***&gt;; 
发送时间: 2022年3月30日(星期三) 上午10:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taozh2017/SPNet] Performance on DUT (Issue #4)





 
Which evaluation toolbox do you use? There is a little difference between Python evaluation and Matlab version.

**Comment by Angknpng** [comment]
This is the test results I got on Matlab Evaluation Toolbox. The NLPR result is very close to what you gave, but the other two are quite different from what you gave. But I tested the predictions using the code and model you provided on github. For a fair comparison, I hope you can provide the results of DUT




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taozh2017/SPNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [taozh2017/SPNet] Performance on DUT (Issue #4)





 
Which evaluation toolbox do you use? There is a little difference between Python evaluation and Matlab version.

**Comment by taozh2017** [comment]
OK. When I am free and I test it on DUT. I can also show the results using the Matlab evaluation toolbox, the difference is very samll.

**Comment by taozh2017** [comment]
OK. When I am free and I test it on DUT. I can also show the results using the Matlab evaluation toolbox, the difference is very small.

**Comment by Angknpng** [comment]
Thank you for your reply and I really appreciate the SPNet you designed. I look forward to your results presentation.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tao ***@***.***&gt;; 
发送时间: 2022年3月30日(星期三) 中午1:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taozh2017/SPNet] Performance on DUT (Issue #4)





 
OK. When I am free and I test it on DUT. I can also show the results using the Matlab evaluation toolbox, the difference is very small.

**Comment by taozh2017** [comment]
> Thank you for your reply and I really appreciate the SPNet you designed. I look forward to your results presentation.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tao ***@***.***&gt;; 发送时间: 2022年3月30日(星期三) 中午1:22 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [taozh2017/SPNet] Performance on DUT (Issue #4) OK. When I am free and I test it on DUT. I can also show the results using the Matlab evaluation toolbox, the difference is very small. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Can you provide your email? and then I send you the predicted maps of DUT-RGBD. Thanks.

**Comment by Angknpng** [comment]
Thank you! my email is ***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tao ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 晚上8:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taozh2017/SPNet] Performance on DUT (Issue #4)





  
Thank you for your reply and I really appreciate the SPNet you designed. I look forward to your results presentation.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tao @.&gt;; 发送时间: 2022年3月30日(星期三) 中午1:22 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [taozh2017/SPNet] Performance on DUT (Issue #4) OK. When I am free and I test it on DUT. I can also show the results using the Matlab evaluation toolbox, the difference is very small. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Can you provide your email? and then I send you the predicted maps of DUT-RGBD. Thanks.

**Comment by taozh2017** [comment]
Your email is blocked. You go to my website and find my email.

**Comment by Angknpng** [comment]
OK. I will send a e-mail to you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tao ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 晚上9:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [taozh2017/SPNet] Performance on DUT (Issue #4)





 
Your email is blocked. You go to my website and find my email.
